### PR TITLE
Filename changes OMPS, VIIRS SST, GMI: feature/rel.satingest.v4.1.0_omps_avhrrsst_gmi

### PR DESCRIPTION
**Pull request by ilianagenkova**
1)OMPS and VIIRS SST filename changes will be updated with a NESDIS NDE upgrade. Prepare fix files for this change.
   This change was submitted as ACDF #134 for WCOSS (to be implemented on 31 May 2022)

2)Filenames  for GMI files changed on May,9, 2022. Reflect this filename change after the fact. 
   This change won't be applied to WCOSS code , as GMI is not operationally used, and WCOSS has 1 month lifetime left

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@SudhirNadiga-NOAA , the npp line is just above, in line 14, unaltered. The j01 line, line 15, is changed only to include the \ character to indicate more filename patterns on successive lines.

**Comment by ShelleyMelchior-NOAA** [comment]
This PR looks good to me!

**Review by SteveStegall-NOAA — APPROVED** [review]

**Review by ilianagenkova — COMMENTED** [review]
Shelley, Iliana and Sudhir reviewed and ok-ed.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
PR looks good

**Comment by ShelleyMelchior-NOAA** [comment]
Approved; merging!

**Pull request merged**
